# Generated by Django 3.0.8 on 2020-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200916_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postedOn',
        ),
        migrations.AlterField(
            model_name='post',
            name='postBody',
            field=models.TextField(default='Enter Post Message'),
        ),
    ]
