# Generated by Django 3.0.8 on 2020-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200917_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
