# Generated by Django 3.0.8 on 2020-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200920_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentedWhen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
